version: '3.8'

services:
  vmware-vm-list:
    build: .
    environment:
      - VCENTER_SERVER=${VCENTER_SERVER}
      - VCENTER_USERNAME=${VCENTER_USERNAME}
      - VCENTER_PASSWORD=${VCENTER_PASSWORD}
    command: >
      python list_vms.py
      --server ${VCENTER_SERVER}
      --username ${VCENTER_USERNAME}
      --password ${VCENTER_PASSWORD}
      --skip-verification
    volumes:
      - ./logs:/app/logs 