version: '3.8'

services:
  vmware-mcp-server-clean:
    build: .
    environment:
      - VCENTER_HOST=${VCENTER_HOST}
      - VCENTER_USER=${VCENTER_USER}
      - VCENTER_PASSWORD=${VCENTER_PASSWORD}
      - VCENTER_INSECURE=${VCENTER_INSECURE}
    stdin_open: true
    tty: true
    volumes:
      - ./logs:/app/logs 