version: '3.8'

services:
  vmware-mcp-server-clean:
    build: ./mcp-server
    environment:
      - VCENTER_SERVER=${VCENTER_SERVER}
      - VCENTER_USERNAME=${VCENTER_USERNAME}
      - VCENTER_PASSWORD=${VCENTER_PASSWORD}
      - VCENTER_INSECURE=${VCENTER_INSECURE:-false}
    stdin_open: true
    tty: true
    volumes:
      - ./logs:/app/logs 